---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" #设置为为default storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.4.34
  share: /mnt/demo2
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
